language: cpp
sudo: required
dist: xenial
compiler:
  - gcc

before_install:
  - sudo apt-get install -y xorg-dev libglu1-mesa-dev
  - sudo apt-get install -y libxmu-dev libxi-dev
  - sudo apt-get install -y python3 python3-pip
  - git clone https://github.com/glfw/glfw.git
  - cd glfw && mkdir build && cd build
  - cmake .. && make && sudo make install
  - cd ../..
  - git clone https://github.com/g-truc/glm.git
  - cd glm && git checkout 0.9.9.5
  - mkdir build && cd build
  - cmake -DBUILD_STATIC_LIBS=OFF -DBUILD_SHARED_LIBS=OFF -DGLM_TEST_ENABLE=OFF ..
  - make && sudo make install
  - cd ../..

script:
  - mkdir build && cd build
  - cmake .. && cmake --build .
  - cd ..

after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git submodule update --init -- "jekyll/_site"
  - cd jekyll/_site
  - git checkout gh-pages
  - cd ..
  - bundle install
  - jekyll build
  - cd _site
  - git add --all
  - git commit -m "Commit from Travis CI for build $TRAVIS_BUILD_NUMBER ."
  - git push --force --quiet https://$GH_TOKEN@github.com/tatsy/OpenGLCourseJP.git gh-pages:gh-pages

git:
  submodules: false

branches:
  only:
    - master
    - development

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
